-- Crear usuario de aplicación antes de crear tablas
DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM dba_users WHERE username = 'APP_USER';
  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER APP_USER IDENTIFIED BY app_password DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER APP_USER ACCOUNT UNLOCK';
    EXECUTE IMMEDIATE 'ALTER USER APP_USER IDENTIFIED BY app_password';
    EXECUTE IMMEDIATE 'ALTER USER APP_USER DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP';
    EXECUTE IMMEDIATE 'ALTER USER APP_USER QUOTA UNLIMITED ON USERS';
  END IF;
END;
/

GRANT CREATE SESSION TO APP_USER;
GRANT RESOURCE TO APP_USER;
GRANT CREATE TABLE TO APP_USER;
GRANT CREATE SEQUENCE TO APP_USER;
GRANT CREATE VIEW TO APP_USER;
GRANT CREATE TRIGGER TO APP_USER;
