-- Creacion de esquema base
ALTER SESSION SET CURRENT_SCHEMA=APP_USER;

CREATE TABLE BASE_DATOS (
  ID_BD     NUMBER(6)    PRIMARY KEY,
  NOMBRE_BD VARCHAR2(100) NOT NULL
);

MERGE INTO BASE_DATOS d
USING (SELECT 1 AS ID_BD, 'AGENCIA DE VIAJES' AS NOMBRE_BD FROM dual) s
   ON (d.ID_BD = s.ID_BD)
WHEN NOT MATCHED THEN
  INSERT (ID_BD, NOMBRE_BD) VALUES (s.ID_BD, s.NOMBRE_BD);

-- DDL de las tablas

-- SUCURSAL
CREATE TABLE SUCURSAL_AV (
  ID_BD        NUMBER(6)    DEFAULT 1 NOT NULL,
  COD_SUCURSAL VARCHAR2(10) NOT NULL,
  DIRECCION    VARCHAR2(120) NOT NULL,
  TELEFONO     VARCHAR2(30),
  CONSTRAINT PK_SUCURSAL_AV PRIMARY KEY (ID_BD, COD_SUCURSAL),
  CONSTRAINT FK_SUCURSAL_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD)
);

-- HOTEL
CREATE TABLE HOTEL_AV (
  ID_BD          NUMBER(6)    DEFAULT 1 NOT NULL,
  COD_HOTEL      VARCHAR2(10) NOT NULL,
  NOMBRE         VARCHAR2(80) NOT NULL,
  DIRECCION      VARCHAR2(120),
  CIUDAD         VARCHAR2(60),
  TELEFONO       VARCHAR2(30),
  PLAZAS_TOTALES NUMBER(5)    NOT NULL CHECK (PLAZAS_TOTALES >= 0),
  CONSTRAINT PK_HOTEL_AV PRIMARY KEY (ID_BD, COD_HOTEL),
  CONSTRAINT FK_HOTEL_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD)
);

-- VUELO
CREATE TABLE VUELO_AV (
  ID_BD           NUMBER(6)    DEFAULT 1 NOT NULL,
  NUM_VUELO       VARCHAR2(12) NOT NULL,
  FECHA_HORA      TIMESTAMP    NOT NULL,
  ORIGEN          VARCHAR2(60) NOT NULL,
  DESTINO         VARCHAR2(60) NOT NULL,
  PLAZAS_TOTALES  NUMBER(5)    NOT NULL CHECK (PLAZAS_TOTALES >= 0),
  PLAZAS_TURISTA  NUMBER(5)    NOT NULL,
  CONSTRAINT PK_VUELO_AV PRIMARY KEY (ID_BD, NUM_VUELO),
  CONSTRAINT FK_VUELO_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD)
  ,CONSTRAINT CK_VUELO_PLAZAS CHECK (PLAZAS_TURISTA >= 0 AND PLAZAS_TURISTA <= PLAZAS_TOTALES)
);

-- TURISTA
CREATE TABLE TURISTA_AV (
  ID_BD            NUMBER(6)    DEFAULT 1 NOT NULL,
  COD_TURISTA      VARCHAR2(12) NOT NULL,
  NOMBRE1          VARCHAR2(40) NOT NULL,
  NOMBRE2          VARCHAR2(40),
  NOMBRE3          VARCHAR2(40),
  APELLIDO1        VARCHAR2(40) NOT NULL,
  APELLIDO2        VARCHAR2(40),
  DIRECCION        VARCHAR2(120),
  PAIS_RESIDENCIA  VARCHAR2(60),
  CONSTRAINT PK_TURISTA_AV PRIMARY KEY (ID_BD, COD_TURISTA),
  CONSTRAINT FK_TURISTA_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD)
);

-- Contactos de TURISTA (multivalorados)
CREATE TABLE TURISTA_TELEFONO_AV (
  ID_BD        NUMBER(6)    DEFAULT 1 NOT NULL,
  COD_TURISTA  VARCHAR2(12) NOT NULL,
  TELEFONO     VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_TURISTA_TELEF_AV PRIMARY KEY (ID_BD, COD_TURISTA, TELEFONO),
  CONSTRAINT FK_TTE_AV_TUR FOREIGN KEY (ID_BD, COD_TURISTA)
    REFERENCES TURISTA_AV(ID_BD, COD_TURISTA) ON DELETE CASCADE,
  CONSTRAINT FK_TTE_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD)
);

CREATE TABLE TURISTA_EMAIL_AV (
  ID_BD        NUMBER(6)    DEFAULT 1 NOT NULL,
  COD_TURISTA  VARCHAR2(12) NOT NULL,
  EMAIL        VARCHAR2(120) NOT NULL,
  CONSTRAINT PK_TURISTA_EMAIL_AV PRIMARY KEY (ID_BD, COD_TURISTA, EMAIL),
  CONSTRAINT FK_TEM_AV_TUR FOREIGN KEY (ID_BD, COD_TURISTA)
    REFERENCES TURISTA_AV(ID_BD, COD_TURISTA) ON DELETE CASCADE,
  CONSTRAINT FK_TEM_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD)
);

-- RESERVA
CREATE TABLE RESERVA_AV (
  ID_BD          NUMBER(6)   DEFAULT 1 NOT NULL,
  ID_RESERVA     NUMBER(19)  GENERATED ALWAYS AS IDENTITY,
  FECHA_RESERVA  DATE        DEFAULT SYSDATE NOT NULL,
  COD_TURISTA    VARCHAR2(12) NOT NULL,
  COD_SUCURSAL   VARCHAR2(10) NOT NULL,
  CONSTRAINT PK_RESERVA_AV PRIMARY KEY (ID_BD, ID_RESERVA),
  CONSTRAINT FK_RES_AV_TUR FOREIGN KEY (ID_BD, COD_TURISTA)
    REFERENCES TURISTA_AV(ID_BD, COD_TURISTA),
  CONSTRAINT FK_RES_AV_SUC FOREIGN KEY (ID_BD, COD_SUCURSAL)
    REFERENCES SUCURSAL_AV(ID_BD, COD_SUCURSAL),
  CONSTRAINT FK_RES_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD)
);

-- ESTADIA (por reserva y hotel)
CREATE TABLE ESTADIA_AV (
  ID_BD          NUMBER(6)    DEFAULT 1 NOT NULL,
  ID_RESERVA     NUMBER(19)   NOT NULL,
  COD_HOTEL      VARCHAR2(10) NOT NULL,
  FECHA_LLEGADA  DATE         NOT NULL,
  FECHA_PARTIDA  DATE         NOT NULL,
  REGIMEN        VARCHAR2(20) NOT NULL CHECK (REGIMEN IN ('MEDIA_PENSION','PENSION_COMPLETA')),
  CONSTRAINT PK_ESTADIA_AV PRIMARY KEY (ID_BD, ID_RESERVA, COD_HOTEL, FECHA_LLEGADA),
  CONSTRAINT FK_EST_AV_RES FOREIGN KEY (ID_BD, ID_RESERVA)
    REFERENCES RESERVA_AV(ID_BD, ID_RESERVA) ON DELETE CASCADE,
  CONSTRAINT FK_EST_AV_HOT FOREIGN KEY (ID_BD, COD_HOTEL)
    REFERENCES HOTEL_AV(ID_BD, COD_HOTEL),
  CONSTRAINT FK_EST_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD),
  CONSTRAINT CK_EST_AV_FECHAS CHECK (FECHA_LLEGADA < FECHA_PARTIDA)
);

-- RESERVA_VUELO (segmentos)
CREATE TABLE RESERVA_VUELO_AV (
  ID_BD        NUMBER(6)    DEFAULT 1 NOT NULL,
  ID_RESERVA   NUMBER(19)   NOT NULL,
  NUM_VUELO    VARCHAR2(12) NOT NULL,
  SECUENCIA    NUMBER(4)    DEFAULT 1 NOT NULL,
  CLASE        VARCHAR2(10) NOT NULL CHECK (CLASE IN ('TURISTA','PRIMERA')),
  CONSTRAINT PK_RV_AV PRIMARY KEY (ID_BD, ID_RESERVA, NUM_VUELO, SECUENCIA),
  CONSTRAINT FK_RV_AV_RES FOREIGN KEY (ID_BD, ID_RESERVA)
    REFERENCES RESERVA_AV(ID_BD, ID_RESERVA) ON DELETE CASCADE,
  CONSTRAINT FK_RV_AV_VUE FOREIGN KEY (ID_BD, NUM_VUELO)
    REFERENCES VUELO_AV(ID_BD, NUM_VUELO),
  CONSTRAINT FK_RV_AV_BD FOREIGN KEY (ID_BD) REFERENCES BASE_DATOS(ID_BD)
);
