ALTER SESSION SET CURRENT_SCHEMA=APP_USER;

CREATE TABLE USUARIOS_APP (
  ID_USUARIO      NUMBER(19) GENERATED ALWAYS AS IDENTITY,
  USERNAME        VARCHAR2(50) NOT NULL UNIQUE,
  PASSWORD_HASH   VARCHAR2(120) NOT NULL,
  NOMBRE_COMPLETO VARCHAR2(120),
  ROL             VARCHAR2(30) DEFAULT 'USUARIO' NOT NULL,
  ACTIVO          CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S','N')),
  CONSTRAINT PK_USUARIOS_APP PRIMARY KEY (ID_USUARIO)
);
