-- Grants y cuota para APP_USER ejecutados como SYSTEM
GRANT CREATE SESSION TO APP_USER;
GRANT CREATE TABLE TO APP_USER;
GRANT CREATE VIEW TO APP_USER;
GRANT CREATE SEQUENCE TO APP_USER;
GRANT CREATE TRIGGER TO APP_USER;
ALTER USER APP_USER QUOTA UNLIMITED ON USERS;
